(function() {
  'use strict';

  angular.module('linagora.esn.chat', [
    'mgcrea.ngStrap.modal',
    'esn.cache',
    'esn.core',
    'esn.router',
    'esn.pagination',
    'restangular',
    'esn.collaboration',
    'esn.search',
    'esn.attachment',
    'esn.attachment-list',
    'esn.provider',
    'esn.scroll',
    'esn.attendee',
    'esn.header',
    'esn.highlight',
    'esn.sidebar',
    'esn.user',
    'op.dynamicDirective',
    'esn.url',
    'esn.lodash-wrapper',
    'esn.oembed',
    'esn.oembed.image',
    'angular-web-notification',
    'esn.localstorage',
    'esn.file',
    'ui.router',
    'angularFileUpload',
    'linagora.esn.emoticon',
    'linagora.esn.user-status',
    'xeditable',
    'angularMoment',
    'ngSanitize',
    'esn.attachment',
    'luegg.directives',
    'zInfiniteScroll',
    'angular-inview',
    'esn.module-registry',
    'esn.datetime',
    'esn.app-state',
    'esn.configuration',
    'esn.message'
  ]);
})();
